name: Run Tests on Commit & PR

on:
  push:
    branches:
      - master
      - feature/add_ci_with_tests
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-pyproject-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .

      - name: Run tests
        run: python -m unittest DSLTools.tests.core_tests.scanner_tests.TestDefaultScanner.test_tokenize_invalid_input -v
      
      - name: Generate JUnit report
        run: |
          pip install xmlrunner
          python -c "
          import unittest
          import xmlrunner
          loader = unittest.TestLoader()
          suite = loader.discover('DSLTools/tests/core_tests/')
          with open('test-results.xml', 'wb') as output:
              runner = xmlrunner.XMLTestRunner(output=output)
              runner.run(suite)
          "

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: test-results.xml
            
            - name: Publish Test Results
              uses: EnricoMi/publish-unit-test-result-action@v2
              if: always()
              with:
                files: test-results.xml